"""Grundschema Inventur

Revision ID: 4dfbc63f19b2
Revises: 
Erstellt: 2026-08-13 02:06:58.415802
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4dfbc63f19b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filial_nr', sa.String(length=10), nullable=False),
    sa.Column('filiale', sa.String(length=120), nullable=False),
    sa.Column('bezeichnung', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('abgeschlossen_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_protokoll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventur_id', sa.Integer(), nullable=False),
    sa.Column('dateiname', sa.String(length=200), nullable=False),
    sa.Column('zeilen_gelesen', sa.Integer(), nullable=False),
    sa.Column('zeilen_importiert', sa.Integer(), nullable=False),
    sa.Column('zeilen_uebersprungen', sa.Integer(), nullable=False),
    sa.Column('spaltenzuordnung', sa.Text(), nullable=False),
    sa.Column('hinweise', sa.Text(), nullable=False),
    sa.Column('importiert_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventur_id'], ['inventur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sollposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventur_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('artikelnummer', sa.String(length=40), nullable=False),
    sa.Column('artikelname', sa.String(length=160), nullable=False),
    sa.Column('marke', sa.String(length=60), nullable=False),
    sa.Column('warengruppe', sa.String(length=60), nullable=True),
    sa.Column('farbnummer', sa.String(length=20), nullable=False),
    sa.Column('farbe', sa.String(length=60), nullable=False),
    sa.Column('groesse', sa.String(length=20), nullable=False),
    sa.Column('vk_preis', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buchbestand', sa.Integer(), nullable=False),
    sa.Column('saison', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['inventur_id'], ['inventur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventur_id', 'artikelnummer', 'farbnummer', 'groesse', name='uq_sollposition_sku')
    )
    with op.batch_alter_table('sollposition', schema=None) as batch_op:
        batch_op.create_index('ix_sollposition_ean', ['inventur_id', 'ean'], unique=False)
        batch_op.create_index('ix_sollposition_suche', ['inventur_id', 'artikelnummer'], unique=False)

    op.create_table('zaehlbereich',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventur_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('zugewiesen_an', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['inventur_id'], ['inventur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventur_id', 'name', name='uq_bereich_name')
    )
    op.create_table('scan_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventur_id', sa.Integer(), nullable=False),
    sa.Column('zaehlbereich_id', sa.Integer(), nullable=True),
    sa.Column('sollposition_id', sa.Integer(), nullable=True),
    sa.Column('roh_code', sa.String(length=64), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('erfassungsart', sa.String(length=20), nullable=False),
    sa.Column('erfasst_von', sa.String(length=80), nullable=False),
    sa.Column('geraet', sa.String(length=80), nullable=True),
    sa.Column('erfasst_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('storniert_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventur_id'], ['inventur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sollposition_id'], ['sollposition.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storniert_event_id'], ['scan_event.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zaehlbereich_id'], ['zaehlbereich.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storniert_event_id', name='uq_scan_storno_einmalig')
    )
    with op.batch_alter_table('scan_event', schema=None) as batch_op:
        batch_op.create_index('ix_scan_inventur', ['inventur_id', 'id'], unique=False)
        batch_op.create_index('ix_scan_position', ['sollposition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_event', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_position')
        batch_op.drop_index('ix_scan_inventur')

    op.drop_table('scan_event')
    op.drop_table('zaehlbereich')
    with op.batch_alter_table('sollposition', schema=None) as batch_op:
        batch_op.drop_index('ix_sollposition_suche')
        batch_op.drop_index('ix_sollposition_ean')

    op.drop_table('sollposition')
    op.drop_table('import_protokoll')
    op.drop_table('inventur')
    # ### end Alembic commands ###
