"""Zonenhierarchie, Vorzaehlung, Benutzer und Markierungen

Revision ID: 5e854441ed13
Revises: 4dfbc63f19b2
Erstellt: 2026-08-13 04:00:42.372114
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '5e854441ed13'
down_revision = '4dfbc63f19b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pin_hash', sa.String(length=200), nullable=False),
    sa.Column('rolle', sa.String(length=20), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sitzung',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('geraet', sa.String(length=120), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('markierung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventur_id', sa.Integer(), nullable=False),
    sa.Column('zaehlbereich_id', sa.Integer(), nullable=True),
    sa.Column('scan_event_id', sa.Integer(), nullable=True),
    sa.Column('sollposition_id', sa.Integer(), nullable=True),
    sa.Column('grund', sa.Text(), nullable=False),
    sa.Column('dringlichkeit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gemeldet_von', sa.String(length=80), nullable=False),
    sa.Column('gemeldet_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('erledigt_von', sa.String(length=80), nullable=True),
    sa.Column('erledigt_am', sa.DateTime(), nullable=True),
    sa.Column('antwort', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inventur_id'], ['inventur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_event_id'], ['scan_event.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sollposition_id'], ['sollposition.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zaehlbereich_id'], ['zaehlbereich.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markierung', schema=None) as batch_op:
        batch_op.create_index('ix_markierung_offen', ['inventur_id', 'status'], unique=False)

    with op.batch_alter_table('inventur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('karte_bild', sa.String(length=200), nullable=True))

    with op.batch_alter_table('zaehlbereich', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eltern_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ebene', sa.String(length=20), server_default='staender', nullable=False))
        batch_op.add_column(sa.Column('soll_teile', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notiz', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bild_pfad', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('karte_x', sa.Numeric(precision=6, scale=4), nullable=True))
        batch_op.add_column(sa.Column('karte_y', sa.Numeric(precision=6, scale=4), nullable=True))
        batch_op.add_column(sa.Column('begonnen_am', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fertig_am', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_bereich_eltern', ['eltern_id'], unique=False)
        batch_op.create_foreign_key('fk_bereich_eltern', 'zaehlbereich', ['eltern_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zaehlbereich', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bereich_eltern', type_='foreignkey')
        batch_op.drop_index('ix_bereich_eltern')
        batch_op.drop_column('fertig_am')
        batch_op.drop_column('begonnen_am')
        batch_op.drop_column('karte_y')
        batch_op.drop_column('karte_x')
        batch_op.drop_column('bild_pfad')
        batch_op.drop_column('notiz')
        batch_op.drop_column('soll_teile')
        batch_op.drop_column('ebene')
        batch_op.drop_column('eltern_id')

    with op.batch_alter_table('inventur', schema=None) as batch_op:
        batch_op.drop_column('karte_bild')

    with op.batch_alter_table('markierung', schema=None) as batch_op:
        batch_op.drop_index('ix_markierung_offen')

    op.drop_table('markierung')
    op.drop_table('sitzung')
    op.drop_table('benutzer')
    # ### end Alembic commands ###
